### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by NothingHere321** [dweltstorm/kahoot-cheat#1]
Make it possible without having tamper monkey installed

**Comment by dweltstorm** [comment]
I'd have to make a chrome extension which is more difficult and could take weeks to get approved. What's wrong with tampermonkey?

**Comment by NothingHere321** [comment]
Can’t use tampermonkey and extension
having a script works better but if you can’t it’s whatever

**Comment by dweltstorm** [comment]
how do you expect to run the  script without tampermonkey or making it into an extension
